defaults:
  - atari
  - override pruning: lth
  - _self_

pruning:
  final_sparsity: 0.6
  pruning_rate: 0.1
  rewind_to_step: 80000

wandb:
  tags: ["atari", "ddqn", "lth"]

train:
  delegate_stopping: true