defaults:
  - algorithm: ddqn
  - env: atari
  - pruning: none
  - train: default
  - _self_

seed: 1
device: "cuda"

wandb:
  enabled: true
  project: "rlp-25"
  entity: null
  group: "ddqn"
  tags: ["baseline", "ddqn", "atari", "breakout"]
  job_type: "train"
  name: "ddqn-baseline"

train:
  save_model: true
  save_sparsity_mask: true

output_dir: ${hydra:runtime.output_dir}