# MinAtar Transfer Experiments
# Self-contained configuration for MinAtar Transfer

defaults:
  - minatar
  - _self_

# Sweep Configuration
# Each item defines an experiment run.
# 'source_pruning': Method used to obtain the source model/mask.
# 'target_pruning': Method used during training on the target environment.
sweep:
  seed:
    - 1
    - 2
    - 3
  
  source_pruning:
    - "random"
    - "gmp"
    - "lth"

  target_pruning:
    - "random"
    - "gmp"
    - "lth"
    - "none" 

  exclude_pruning:
    - {source_pruning: "random", target_pruning: "lth"}
    - {source_pruning: "gmp", target_pruning: "lth"}

  source_sparsity:
    - 0.6
    - 0.7
    - 0.8
    - 0.9


