defaults:
  - algorithm: ddqn
  - env: minatar
  - pruning: none
  - train: default
  - _self_

train:
  total_timesteps: 5000000
  checkpoint_interval: 100000

algorithm:
  network:
    encoder: "minatar_cnn"
    hidden_dim: 128

  tau: 1.0
  learning_starts: 5000
  batch_size: 32
  target_network_frequency: 1000
  train_frequency: 1
  epsilon:
    decay_fraction: 0.1

seed: 1
device: "cuda"

wandb:
  enabled: true
  project: "rlp-25"
  group: "minatar"
  entity: null
  tags: ["minatar", "ddqn"]
  job_type: "train"
