name: Sync docs to Overleaf

on:
  push:
    branches:
      - overleaf-sync
    paths:
      - 'docs/**'
  workflow_dispatch:
jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout project
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Setup Git
      run: |
        git config --global user.name "GitHub Actions"
        git config --global user.email "actions@github.com"
        git config --global init.defaultBranch main

    - name: Setup SSH
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.OVERLEAF_SYNC_SSH_KEY }}" > ~/.ssh/id_ed25519
        chmod 600 ~/.ssh/id_ed25519
        ssh-keyscan github.com >> ~/.ssh/known_hosts

    - name: Setup Sync Local
      run: |
        cd ~
        git clone --depth=1 ${{ secrets.OVERLEAF_PROXY_SSH }} sync

    - name: Sync Local
      run: |
        git fetch origin overleaf-sync
        git checkout overleaf-sync
        cp -r docs/* ~/sync

    - name: Sync Remote
      run: |
        cd ~/sync
        git add .
        git commit -m "[sync:$GITHUB_SHA]
        
        ${{ github.event.head_commit.message }}"
        git push origin main
